# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(535, 190)
        MainWindow.setMinimumSize(QtCore.QSize(535, 190))
        MainWindow.setMaximumSize(QtCore.QSize(535, 190))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Version = QtWidgets.QLabel(self.centralwidget)
        self.Version.setGeometry(QtCore.QRect(10, 10, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(15)
        self.Version.setFont(font)
        self.Version.setObjectName("Version")
        self.Check = QtWidgets.QPushButton(self.centralwidget)
        self.Check.setGeometry(QtCore.QRect(10, 50, 121, 41))
        self.Check.setAutoDefault(True)
        self.Check.setDefault(True)
        self.Check.setObjectName("Check")
        self.Submit = QtWidgets.QPushButton(self.centralwidget)
        self.Submit.setEnabled(False)
        self.Submit.setGeometry(QtCore.QRect(10, 100, 121, 41))
        self.Submit.setObjectName("Submit")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 150, 121, 31))
        self.lineEdit.setWhatsThis("")
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(140, 11, 391, 171))
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "易班IP工具"))
        self.Version.setText(_translate("MainWindow", "易班IP工具"))
        self.Check.setText(_translate("MainWindow", "链接IP池"))
        self.Submit.setText(_translate("MainWindow", "提交信息"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "请输入Appid"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">本工具由<a href=\"https://github.com/Lord2333\"><span style=\" font-weight:600; text-decoration: underline; color:#0000ff;\">Lord2333</span></a>开发，使用Pyqt作为可视化框架</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">仅供学习交流使用！</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">项目地址：<a href=\"https://github.com/Lord2333/YB_IPtool\"><span style=\" text-decoration: underline; color:#0000ff;\">https://github.com/Lord2333/YB_IPtool</span></a></p></body></html>"))
