# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'update.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(250, 130)
        Dialog.setMinimumSize(QtCore.QSize(250, 130))
        Dialog.setMaximumSize(QtCore.QSize(250, 130))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.Check_info = QtWidgets.QLabel(Dialog)
        self.Check_info.setGeometry(QtCore.QRect(11, 10, 231, 70))
        self.Check_info.setAlignment(QtCore.Qt.AlignCenter)
        self.Check_info.setObjectName("Check_info")
        self.Comfirm = QtWidgets.QPushButton(Dialog)
        self.Comfirm.setGeometry(QtCore.QRect(10, 90, 111, 31))
        self.Comfirm.setObjectName("Comfirm")
        self.Ignore = QtWidgets.QPushButton(Dialog)
        self.Ignore.setGeometry(QtCore.QRect(140, 90, 101, 31))
        self.Ignore.setObjectName("Ignore")

        self.retranslateUi(Dialog)
        self.Comfirm.clicked.connect(Dialog.accept)
        self.Ignore.clicked.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "有船新版本辣"))
        self.Check_info.setText(_translate("Dialog", "Laoding..."))
        self.Comfirm.setText(_translate("Dialog", "去更新！"))
        self.Ignore.setText(_translate("Dialog", "将就用着"))
